language: java

dist: xenial

services:
  - docker

before_cache:
  - rm -rf $HOME/.m2/repository/com/plugins/grafana/snapshot*

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - JAVA_LEVEL=8

matrix:
  include:
    - jdk: openjdk11
      env:
        - MVN_FLAG='-Djenkins.version=2.164.3 -Daccess-modifier-checker.failOnError=true'
    - jdk: openjdk8
      env:
        - MVN_FLAG='-Djenkins.version=2.164.3 -Daccess-modifier-checker.failOnError=true'
    - jdk: openjdk8

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
script:
  - |
    mvn clean install

notifications:
  email: false
